name: py-corona-2-ensemble
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - arrow-cpp=0.11.1=py36h3bd774a_1
  - arviz=0.6.1=py_0
  - asyncssh=2.1.0=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - bcrypt=3.1.7=py36h7b6447c_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=1.0=mkl
  - bleach=3.1.4=pyh9f0ad1d_0
  - blosc=1.16.3=hd408876_0
  - bokeh=2.0.1=py36_0
  - boost-cpp=1.68.0=h11c811c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0=py36hd463f26_0
  - cftime=1.1.1.1=py36heb32a55_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - chart-studio=1.1.0=pyh9f0ad1d_0
  - click=7.1.1=py_0
  - cloudpickle=1.3.0=py_0
  - colorlover=0.3.0=py_0
  - conda-pack=0.4.0=py_0
  - cryptography=2.8=py36h45558ae_2
  - cufflinks-py=0.17.3=py_0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.1=py36h516909a_0
  - dash=1.4.1=py_0
  - dash-core-components=1.3.1=py_0
  - dash-html-components=1.0.1=py_0
  - dash-renderer=1.1.2=py_0
  - dash-table=4.4.1=py_0
  - dask=2.14.0=py_0
  - dask-core=2.14.0=py_0
  - dask-yarn=0.8.1=py36h9f0ad1d_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.14.0=py36h9f0ad1d_0
  - entrypoints=0.3=py36_0
  - fastparquet=0.3.3=py36hc1659b7_0
  - flask=1.1.1=py_1
  - flask-compress=1.4.0=py_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.7.1=py_0
  - future=0.18.2=py36_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - grpcio=1.23.0=py36h769ab6c_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.10.0=py36h7918eee_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - itsdangerous=1.1.0=py36_0
  - jedi=0.16.0=py36_1
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py36_0
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libevent=2.1.10=h72c5cf5_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_0
  - libllvm8=8.0.1=hc9558a2_0
  - libnetcdf=4.7.3=hb80b6cc_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - llvmlite=0.31.0=py36hfa65bc7_1
  - locket=0.2.0=py36_1
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - mako=1.1.2=py_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h516909a_1000
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - mock=4.0.1=py_0
  - msgpack-python=1.0.0=py36hdb11119_1
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - netcdf4=1.5.3=py36hbf33ddf_0
  - notebook=6.0.3=py36_0
  - numba=0.48.0=py36hb3f55d8_0
  - numexpr=2.7.1=py36h423224d_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - olefile=0.46=py36_0
  - openssl=1.1.1f=h7b6447c_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py36h0573a6f_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - paramiko=2.7.1=py_0
  - parquet-cpp=1.5.1=3
  - parso=0.6.2=py_0
  - partd=1.1.0=py_0
  - patsy=0.5.1=py36_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py36_1
  - plotly=4.5.2=py_0
  - plotly-orca=1.2.1=1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - protobuf=3.11.4=py36h831f99a_1
  - psutil=5.7.0=py36h8c4c3a4_1
  - ptyprocess=0.6.0=py36_0
  - pyarrow=0.11.1=py36hbbcf98d_1002
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pygpu=0.7.6=py36h035aef0_0
  - pymc3=3.8=py_0
  - pynacl=1.3.0=py36h7b6447c_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.16.0=py36h7b6447c_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - pytables=3.6.1=py36h71ec239_0
  - python=3.6.10=hcf32534_1
  - python-cufflinks=0.17.3=py_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - pyzmq=18.1.1=py36he6710b0_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=pyh8c360ce_2
  - retrying=1.3.3=py36_2
  - scikit-learn=0.22.1=py36hd81dba3_0
  - scipy=1.4.1=py36h0b6359f_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py36_0
  - six=1.14.0=py36_0
  - skein=0.8.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.31.1=h7b6447c_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - theano=1.0.4=py36hfd86e86_0
  - thrift=0.11.0=py36he1b5a44_1001
  - thrift-cpp=0.11.0=h02b749d_3
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.44.1=py_0
  - traitlets=4.3.3=py36_0
  - typing_extensions=3.7.4.1=py36_0
  - urllib3=1.25.7=py36h9f0ad1d_1
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xarray=0.15.0=py_0
  - xlrd=1.2.0=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/ec2-user/.conda/envs/py-corona-2-ensemble

